---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: forbid-new-submodules
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
        - id: git-secrets
          name: git-secrets
          entry: git-secrets
          language: system
          args: ["--scan"]
  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        entry: hadolint
        language: system
        exclude: ^Dockerfile.alpine.unpinned, ^Dockerfile.slim.unpinned
        files: ^Dockerfile.alpine, ^Dockerfile.slim
