FROM twdps/circleci-base-image:slim-7.1.0

LABEL org.opencontainers.image.title="circleci-infra-aws" \
      org.opencontainers.image.description="Debian-based CircleCI executor image" \
      org.opencontainers.image.documentation="https://github.com/ThoughtWorks-DPS/circleci-infra-aws" \
      org.opencontainers.image.source="https://github.com/ThoughtWorks-DPS/circleci-infra-aws" \
      org.opencontainers.image.url="https://github.com/ThoughtWorks-DPS/circleci-infra-aws" \
      org.opencontainers.image.vendor="ThoughtWorks, Inc." \
      org.opencontainers.image.authors="nic.cheneweth@thoughtworks.com" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created="CREATED" \
      org.opencontainers.image.version="VERSION"

ENV TERRAFORM_VERSION=1.7.5
ENV TERRAFORM_SHA256SUM=3ff056b5e8259003f67fd0f0ed7229499cfb0b41f3ff55cc184088589994f7a5
ENV TFLINT_VERSION=0.50.3
ENV TFSEC_VERSION=1.28.5
ENV TRIVY_VERSION=0.49.1
ENV AWSCLI_VERSION=1.32.25
ENV CHECKOV_VERSION=3.2.38
ENV DRIFTCTL_VERSION=0.40.0
ENV CIRCLEPIPE_VERSION=0.3.2
ENV COSIGN_VERSION=2.2.3
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

# sudo since twdps circleci base images set the USER=cirlceci
# hadolint ignore=DL3004
RUN sudo apt-get update && sudo apt-get install --no-install-recommends -y \
                 nodejs=18.19.1+dfsg-6 \
                 npm=9.2.0~ds1-2 \
                 ruby-full=1:3.1 \
                 python3-dev=3.11.8-1 \
                 python3-pip \
                 python3-venv=3.11.8-1 && \
    sudo ln -f -s /usr/bin/pip3 /usr/bin/pip && \
    sudo ln -f -s /usr/bin/pydoc3 /usr/bin/pydoc && \
    sudo ln -f -s /usr/bin/python3 /usr/bin/python && \
    sudo ln -f -s /usr/bin/python3-config /usr/bin/python-config && \
    sudo pip install --no-cache-dir --break-system-packages setuptools==69.2.0 && \
    sudo pip install --no-cache-dir --break-system-packages \
             invoke==2.2.0 \
             requests==2.31.0 \
             jinja2==3.1.3 \
             iam-credential-rotation==0.2.2 \
             awscli==${AWSCLI_VERSION} \
             checkov==${CHECKOV_VERSION} && \
    sudo gem install --no-document \
             awspec:1.29.3 \
             inspec-bin:5.22.36 \
             json:2.7.1 && \
    sudo npm install -g \
             snyk@1.1284.0 \
             github-release-notes@0.17.3 \
             bats@1.10.0 && \
    curl -SLO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > "terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
    echo "${TERRAFORM_SHA256SUM}  terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > "terraform_${TERRAFORM_VERSION}_SHA256SUMS" && \
    sha256sum -c "terraform_${TERRAFORM_VERSION}_SHA256SUMS" && sudo rm "terraform_${TERRAFORM_VERSION}_SHA256SUMS" && \
    sudo unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -d /usr/local/bin && \
    sudo rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
    curl -SLO "https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip" > tflint_linux_amd64.zip && \
    sudo unzip tflint_linux_amd64.zip -d /usr/local/bin && \
    sudo rm tflint_linux_amd64.zip && \
    curl -SLO https://github.com/aquasecurity/tfsec/releases/download/v${TFSEC_VERSION}/tfsec-linux-amd64 && \
    chmod +x tfsec-linux-amd64 && \
    sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec && \
    curl -LO https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz && \
    tar xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz trivy && \
    sudo mv trivy /usr/local/bin && rm trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz && \
    curl -L https://github.com/snyk/driftctl/releases/download/v${DRIFTCTL_VERSION}/driftctl_linux_amd64 -o driftctl && \
    chmod +x driftctl && \
    sudo mv driftctl /usr/local/bin/driftctl && \
    curl -SLO https://github.com/ThoughtWorks-DPS/circlepipe/releases/download/${CIRCLEPIPE_VERSION}/circlepipe_Linux_amd64.tar.gz && \
    mkdir ./circlepipe && tar -xzf circlepipe_Linux_amd64.tar.gz -C ./circlepipe && \
    sudo mv ./circlepipe/circlepipe /usr/local/bin/circlepipe && \
    sudo rm -rf ./circlepipe circlepipe_Linux_amd64.tar.gz && \
    curl -LO https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64 && \
    chmod +x cosign-linux-amd64 && sudo mv cosign-linux-amd64 /usr/local/bin/cosign && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*

COPY inspec /etc/chef/accepted_licenses/inspec

USER circleci
