FROM twdps/circleci-base-image:slim-3.1.2

LABEL maintainers=<nic.cheneweth@thoughtworks.com>

ENV TERRAFORM_VERSION=1.0.5
ENV TERRAFORM_SHA256SUM=7ce24478859ab7ca0ba4d8c9c12bb345f52e8efdc42fa3ef9dd30033dbf4b561
ENV TFLINT_VERSION=0.31.0
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
ENV PATH=/home/circleci/.rbenv/bin:$PATH:/usr/local/go/bin:/home/circleci/.cargo/bin
ENV GOPATH=/home/circleci/.go

# sudo since twdps circleci base images set the USER=cirlceci
# hadolint ignore=DL3004
RUN sudo apt-get update && sudo apt-get install --no-install-recommends -y \
                 curl=7.74.0-1.3+b1 \
                 wget=1.21-1+b1 \
                 gnupg=2.2.27-2 \
                 jq=1.6-2.1 \
                 bzip2=1.0.8-4 \
                 unzip=6.0-26 \
                 ruby-full=1:2.7+2 \
                 python3-dev=3.9.2-3 \
                 python3-pip \
                 python3-venv=3.9.2-3 \
                 lsb-release=11.1.0 \
                 gcc=4:10.2.1-1 \
                 g++=4:10.2.1-1 \
                 make=4.3-4.1 && \
    sudo bash -c "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg" && \
    sudo bash -c "echo \"deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \$(lsb_release -cs) stable\" | tee /etc/apt/sources.list.d/docker.list > /dev/null" && \
    sudo apt-get update && sudo apt-get install --no-install-recommends -y \
                 docker-ce=5:20.10.7~3-0~debian-bullseye \
                 docker-ce-cli=5:20.10.7~3-0~debian-bullseye \
                 containerd.io=1.4.6-1 && \
    sudo bash -c "curl -sL https://deb.nodesource.com/setup_14.x | bash - " && \
    sudo apt-get install --no-install-recommends -y \
                 nodejs=14.17.6-deb-1nodesource1 && \
    sudo ln -f -s /usr/bin/pip3 /usr/bin/pip && \
    sudo ln -f -s /usr/bin/pydoc3 /usr/bin/pydoc && \
    sudo ln -f -s /usr/bin/python3 /usr/bin/python && \
    sudo ln -f -s /usr/bin/python3-config /usr/bin/python-config && \
    pip install --no-cache-dir setuptools==57.4.0 && \
    pip install --no-cache-dir \
        wheel==0.37.0 \
        awscli==1.20.30 \
        invoke==1.6.0 \
        requests==2.26.0 \
        jinja2==3.0.1 && \
    sudo gem install --no-document \
             awspec:1.24.4 \
             inspec-bin:4.41.2 \
             json:2.5.1 && \
    sudo npm install -g \
             bats@1.4.1 && \
    curl -SLO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > "terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
    echo "${TERRAFORM_SHA256SUM}  terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > "terraform_${TERRAFORM_VERSION}_SHA256SUMS" && \
    sha256sum -c "terraform_${TERRAFORM_VERSION}_SHA256SUMS" && sudo rm "terraform_${TERRAFORM_VERSION}_SHA256SUMS" && \
    sudo unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -d /usr/local/bin && \
    sudo rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip" && \
    curl -SLO "https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip" > tflint_linux_amd64.zip && \
    sudo unzip tflint_linux_amd64.zip -d /usr/local/bin && \
    sudo rm tflint_linux_amd64.zip  && \
    sudo -u circleci mkdir /home/circleci/.gnupg && \
    sudo -u circleci bash -c "echo 'allow-loopback-pinentry' > /home/circleci/.gnupg/gpg-agent.conf" && \
    sudo -u circleci bash -c "echo 'pinentry-mode loopback' > /home/circleci/.gnupg/gpg.conf" && \
    chmod 700 /home/circleci/.gnupg && chmod 600 /home/circleci/.gnupg/* && \
    sudo apt-get clean && \
    sudo rm -rf /var/lib/apt/lists/*

COPY inspec /etc/chef/accepted_licenses/inspec

USER circleci


                #  gcc=4:10.2.1-1 \
                #  g++=4:10.2.1-1 \
                #  make=4.3-4.1 \
                #  libreadline-dev=8.1-1 \
                #  libssl-dev=1.1.1k-1 \
                #  zlib1g-dev=1:1.2.11.dfsg-2 \
                #  autoconf=2.69-14 \
                #  bison=2:3.7.5+dfsg-1 \
                #  libyaml-dev=0.2.2-1 \
                #  libncurses5-dev=6.2+20201114-2 \
                #  libffi-dev=3.3-6 \
                #  libgdbm-dev=1.19-2 \
